codeTable/codeTable/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
	url(r'^codeTable/', include('initial.urls')),
    url(r'^admin/', admin.site.urls),
]

codeTable/initial/urls.py
from django.conf.urls import url

from . import views

app_name = 'initial'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^submitCode', views.submitCode, name='submitCode'),
]

codeTable/initial/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

codeTable/initial/views.py
from django.shortcuts import render
from django.template import RequestContext, loader
from django.views.decorators.csrf import csrf_exempt

# Create your views here.

from django.http import HttpResponse

from parameters import SupportedLanguages
from parameters import RunAPIParameters

from api_handlers import HackerEarthAPI

@csrf_exempt
def index(request):
	template = loader.get_template('initial/index.html')
	
	return HttpResponse(template.render())

def sujay(code, language, inp=None):
	client_secret = '0a7f0101e5cc06e4417a3addeb76164680ac83a4'

	#source = open('test_source.py', 'r').read()
	source=code
	#lang = SupportedLanguages.PYTHON
	lang = language
	compressed = 1
	html = 0
	params = RunAPIParameters(
        client_secret=client_secret, source=source,
        lang=lang, compressed=compressed, html=html, program_input=inp)

	api = HackerEarthAPI(params)

	print 'Compiling code..'
	r = api.compile()
	print r.__dict__
	if r.__dict__.get('compile_status')!='OK':
		return r.__dict__.get('compile_status')

	print '\nRunning code...'
	r = api.run()
	print r.__dict__
	output = r.__dict__.get('output')

	print '\nRun Output:'
	print output
	return output


@csrf_exempt
def submitCode(request):
	code = request.POST['code']
	lang = request.POST['lang']
	inp = ''
	if request.POST.get('checkInput'):
		inp = request.POST['customInput']
		print "INside Herr"
	print inp
	print type(inp)
	#print code
	output = sujay(code, lang, str(inp))
	template = loader.get_template('initial/index.html')
	context = RequestContext(request, {
        'output': output,
    })
	return HttpResponse(template.render(context))

codeTable/initial/templates/initial/index.html
<html>
<head>
<body>
<h1>Sujay CodeTable</h1>
<form action="{% url 'initial:submitCode' %}" method="post">

<!--<input type="text" name="code"/>-->
<textarea name="code" cols="40" rows="10"></textarea>
<br>
<!--<input type="radio" name="lang" value="C" checked>C (gcc 4.8.1)
<br>
<input type="radio" name="lang" value="CPP">C++ (g++ 4.8.1)
<br>
<input type="radio" name="lang" value="CLOJURE">Clojure (clojure 1.1.0)
<br>
<input type="radio" name="lang" value="CSS">CSS
<br>
<input type="radio" name="lang" value="CSHARP">C# (mono 2.10.8.1)
<br>
<input type="radio" name="lang" value="GO">Go (go 1.4.1)
<br>
<input type="radio" name="lang" value="HASKELL">Haskell (ghc 7.4.1)
<br>
<input type="radio" name="lang" value="HTML">HTML
<br>
<input type="radio" name="lang" value="JAVA">Java (openjdk 1.7.0_09)
<br>
<input type="radio" name="lang" value="JAVASCRIPT">JavaScript (Rhino 1.7)
<br>
<input type="radio" name="lang" value="JAVASCRIPT_NODE">JavaScript (Node.js 0.6.12)
<br>
<input type="radio" name="lang" value="LISP">Lisp (csc 4.7.0)
<br>
<input type="radio" name="lang" value="OBJECTIVEC">Objective-C (clang 3.3)
<br>
<input type="radio" name="lang" value="PASCAL">Pascal (fpc 2.4.4)
<br>
<input type="radio" name="lang" value="PERL">Perl (perl 5.14.2)
<br>
<input type="radio" name="lang" value="PHP">PHP (php 5.3.10)
<br>
<input type="radio" name="lang" value="PYTHON">Python (python 2.7.3)
<br>
<input type="radio" name="lang" value="RUBY">Ruby (ruby 2.1.1)
<br>
<input type="radio" name="lang" value="R">R (RScript 2.14.1)
<br>
<input type="radio" name="lang" value="RUST">Rust (rustc 1.4.0)
<br>
<input type="radio" name="lang" value="SCALA">Scala (scalac 2.9.1)
<br>
<input type="radio" name="lang" value="TEXTFILE">Text
<br>-->

<select name="lang">
<option value="C" checked>C (gcc 4.8.1)
<br>
<option  value="CPP">C++ (g++ 4.8.1)
<br>
<option value="CLOJURE">Clojure (clojure 1.1.0)
<br>
<option value="CSS">CSS
<br>
<option value="CSHARP">C# (mono 2.10.8.1)
<br>
<option value="GO">Go (go 1.4.1)
<br>
<option value="HASKELL">Haskell (ghc 7.4.1)
<br>
<option value="HTML">HTML
<br>
<option value="JAVA">Java (openjdk 1.7.0_09)
<br>
<option value="JAVASCRIPT">JavaScript (Rhino 1.7)
<br>
<option value="JAVASCRIPT_NODE">JavaScript (Node.js 0.6.12)
<br>
<option value="LISP">Lisp (csc 4.7.0)
<br>
<option value="OBJECTIVEC">Objective-C (clang 3.3)
<br>
<option value="PASCAL">Pascal (fpc 2.4.4)
<br>
<option value="PERL">Perl (perl 5.14.2)
<br>
<option value="PHP">PHP (php 5.3.10)
<br>
<option value="PYTHON">Python (python 2.7.3)
<br>
<option value="RUBY">Ruby (ruby 2.1.1)
<br>
<option value="R">R (RScript 2.14.1)
<br>
<option value="RUST">Rust (rustc 1.4.0)
<br>
<option value="SCALA">Scala (scalac 2.9.1)
<br>
<option value="TEXTFILE">Text
	
</select>

<input type="checkbox" name="checkInput">Check for custom input</input>
<textarea name="customInput">Enter custom input</textarea>
<input type="submit"/>
</form>

{% if output %}
    <h2>{{ output }}</h2>
{% else %}
    <p>Output</p>
{% endif %}
</body>
</head>
</html>

codeTable/initial/templates/initial/results.html
{% if output %}
    <h2>{{ output }}</h2>
{% else %}
    <p>No output received.</p>
{% endif %}

codeTable/templates/initial/index.html
<html>
<head>
<body>
<h1>Inside initial template</h1>
</body>
</head>
</html>